### ISSUE TITLE
Checklist SBC #7

### ISSUE THREAD

**Issue by fabrik42** [fabrik42/cndy-internal#11]
[Regeln für die Stellar Build Challenge](https://www.stellar.org/lumens/build)

[Announcement für SBC7](https://www.stellar.org/blog/announcing-the-7th-stellar-build-challenge/)

### 1) App Store

- [ ] [App Store Einreichung](https://github.com/fabrik42/cndy-internal/issues/5)

### 2) Marketing

- [x] [Coole Fotos](https://github.com/fabrik42/cndy-internal/issues/3)
- [x] [Real Life usage Video](https://github.com/fabrik42/cndy-internal/issues/9)
- [x] [Screencast](https://github.com/fabrik42/cndy-internal/issues/4)

### 3) Website

- [ ] Analytics frontend dropdown f. multi-asset
- [x] [Update website text](https://github.com/fabrik42/cndy-internal/issues/10)

### 4) Account Creation

- [ ] [Multisig-Paper](https://github.com/fabrik42/cndy-internal/issues/2)
