### ISSUE TITLE
Fragebogen für Build Challenge ausfüllen

### ISSUE THREAD

**Issue by fabrik42** [fabrik42/cndy-internal#8]
Hier die Themen, zu denen wir was schreiben müssen!

--- 
- [x] 20 pre-funded accounts (Link zum PDF wo?)
- [x] CHANGELOG auf [Galactic Talk](https://github.com/fabrik42/cndy-internal/issues/12)? (Darf nicht in die Beschreibung)
- [x] Real World Beta Test mit CNDY coin incl. Fotos und Videos wohin? [Galactic Talk](https://github.com/fabrik42/cndy-internal/issues/12)?
- [x] Gewerbeverein Gespräche in [Galactic Talk](https://github.com/fabrik42/cndy-internal/issues/12)?
---

![screen shot 2018-07-22 at 12 20 29](https://user-images.githubusercontent.com/223822/43044625-e1333936-8da9-11e8-9771-f89a7ba28c45.png)
![screen shot 2018-07-22 at 12 20 53](https://user-images.githubusercontent.com/223822/43044626-e2a7be04-8da9-11e8-8e6e-dc1c674bfe10.png)
![screen shot 2018-07-22 at 12 21 01](https://user-images.githubusercontent.com/223822/43044627-e3e15f8c-8da9-11e8-81d5-e0dbf05290e9.png)
![screen shot 2018-07-22 at 12 21 06](https://user-images.githubusercontent.com/223822/43044628-e5377f92-8da9-11e8-9216-c4b6e4bae070.png)
![screen shot 2018-07-22 at 12 21 19](https://user-images.githubusercontent.com/223822/43044632-e9b0ffd0-8da9-11e8-9537-b00a952b6529.png)
![screen shot 2018-07-22 at 12 21 33](https://user-images.githubusercontent.com/223822/43044633-eafee438-8da9-11e8-8316-ff8aadd368a4.png)
![screen shot 2018-07-22 at 12 21 37](https://user-images.githubusercontent.com/223822/43044634-eca0e70a-8da9-11e8-86a0-57031f9a16b0.png)
![screen shot 2018-07-22 at 12 21 48](https://user-images.githubusercontent.com/223822/43044635-edf076d4-8da9-11e8-826e-4fcfd689d700.png)
![screen shot 2018-07-22 at 12 21 54](https://user-images.githubusercontent.com/223822/43044636-ef226648-8da9-11e8-97d9-dbb4dd09e99f.png)
![screen shot 2018-07-22 at 12 22 05](https://user-images.githubusercontent.com/223822/43044637-f033ee6c-8da9-11e8-8cbc-a044aca2da17.png)

**Comment by fabrik42** [comment]
Das hier habe ich noch von letztem mal:


# How do you summarize your project?*

An ecosystem to create regional crypto currencies to support local businesses in rural areas.

It provides insights and management tools for the issuer and mobile wallets that are easy to use.


# Tell us more about your project!

> This is your opportunity to tell us interesting details about what makes your project unique and what makes it a winner!

In many regions across the world, people (mostly local trade associations) invent their very own [local currency](https://en.wikipedia.org/wiki/Local_currency#List_of_local_currencies), usually to incentivize buying from local businesses.

In most cases, this is achieved using some sort of paper coupons. The process of issuing and distributing such coupons is cumbersome and often degrades the local currency to be used as gift vouchers instead of a real currency that is used in daily life. It is also very hard for local trade associations to track the usage and success of such coupons.

The CNDY (pronounced "candy") project provides the necessary tools to solve these issues. Instead of having to rely on paper coupons, the local community can easily create a virtual currency that is easy to use for everyone!

CNDY can:

- create a custom currency on the Stellar Network
- abstract away creating and funding the underlying Stellar account necessary to use the new currency
- create the necessary trustlines and distribute tokens to the newly created account
- provide a mobile wallet that can be used to easily pay with the local currency
- show insights about the adaption and usage of the currency in real time.

CNDY enhances the Stellar ecosystem to embrace white label currencies, so the end user does not have to bother with the funding of a Stellar account and other technical details.

CNDY creates additional services beyond the possibilities of the traditional paper coupon: Detailed [analytics](http://cndy.store) for the local trade association, transparency by using the Stellar blockchain. It is possible to easily transfer and pay with the new currency, making it a real alternative to the regular currency.

## Example: The CNDY Token

As a proof of concept, we've created a [CNDY token](https://horizon-testnet.stellar.org/assets?asset_issuer=GCJKC2MI63KSQ6MLE6GBSXPDKTDAK43WR522ZYR3F34NPM7Z5UEPIZNX&asset_code=CNDY) on the Stellar Testnet.

The keys required issuer and distributor keys are included in the [CNDY CLI](https://github.com/cndy-store/cli).

Feel free to issue and distribute CNDY tokens as you will! You can track the status of the CNDY coin in realtime on [cndy.store](http://cndy.store).

## Workflow

The issuer of the new currency uses the [CNDY CLI](https://github.com/cndy-store/cli#quickstart-demo-version) (written in NodeJS) to create a custom currency, the necessary accounts for the issuer and distributor and the required trustlines.

Once the currency is created, the CNDY CLI takes away the effort of setting up new accounts for customers. The `account:create:test` creates a new key pair, funds the account on the Stellar Network with a few Lumen, creates a trustline for the custom currency and finally transfers a given amount of the custom currency to the new account. In the end it presents the private key in form of a QR code on the screen of the issuer. All the customer has to do is to scan this QR code with his [CNDY wallet](https://github.com/cndy-store/mobile-wallet) (NOTE: The wallet is not usable yet), and he is ready to use the new currency to purchase goods or share it with other people in the community.

## Known issues

- We've implemented support for streaming Stellar effects for the Stellar Go SDK and filed a [pull-request](https://github.com/stellar/go/pull/343). Feedback is welcome!
- We plan to use Stellars multisig features to ensure the initial funding of new accounts (which is funded by the issuer) can not be exploited while making sure the private key never leaves the customers device

**Comment by chr4** [comment]
## Can you summarize your project

> Avoid words like unique, best, etc. - 140 chars

**With the CNDY ecosystem your local trade association or organic food market can create a digital local currency to support local businesses**


### Other suggestions

> With the CNDY ecosystem your local trade association can create a digital currency to support businesses in your area.

> The CNDY ecosystem enables local trade associations to create their own local crypto currency to support businesses in your area

> CNDY is an ecosystem to support local trade associations and businesses with regional crypto currencies

> CNDY is an user-friendly ecosystem to enable people to create local crypto currencies to support businesses in rural areas

> CNDY is an ecosystem to create regional crypto currencies to support your local trade association

> Roll out a local crypto currency with CNDY!

**Comment by chr4** [comment]
## Time for more detail - what does your project do?

> What makes it unique, don't link to Galactic talk or add a Changelog - 500 chars

CNDY (pronounced "candy") enables trade associations in rural areas and regional organic food markets to create a local currency, enabling their customers to support their local businesses.

Its intention is to provide a safe and easy to use alternative to paper based coupons.

CNDY provides white-labeled mobile apps, detailed insights of the currency usage and adaption in a dashboard and abstracts away all the difficulties of creating and maintaining an asset on the blockchain.

**Comment by chr4** [comment]
## Go in depth on how your project utilizes Stellar

- Custom assets are created on the Stellar blockchain.
- CNDY abstracts away funding of the required Stellar accounts, automatically invokes the required trustline and transfer operations to hand out assets to new customers.
- Our mobile wallets are communicating with Horizon's REST API to view account status and initiate transactions of custom assets on the Stellar network.
- The Analytics Dashboard aggregates blockchain data (via streaming) to allow real time dashboards  for critical statistics of created assets.

- Intents to use Stellars Multi-Sig features to further secure account setup (?)

**Comment by fabrik42** [comment]
Kurze Verständnisfrage: `organic market` steht für Biomarkt? Meinst du da was anderes?

> Can you summarize your project

Da find ich den ersten auch am besten, würde aber das "or ..." wahrscheinlich sogar raus nehmen.

> Go in depth on how your project utilizes Stellar

Man könnte noch adden:

* Stellar provides the ability to create and maintain secure custom assets in an easy way.
* The Horizon REST API is well-suited for clients to communicate directly with the Stellar network.
* Because CNDY is supposed to be used in Point of Sale situations, it is very important to us that a transaction is completed in as little time as possible. Stellar's average transaction time of five seconds got very good responses during our internal tests with real business owners. 
* Bei Analytics vllt noch dazu: Custom aggregations of blockchain data allow real-time dashboards for critical statistics of the individual assets.

**Comment by chr4** [comment]
> Kurze Verständnisfrage: organic market steht für Biomarkt? Meinst du da was anderes?

Exakt. Meinst du da gibt's potentielle Missverständnisse?

Ok, hab die Punkte oben hinzugefügt. Was findest du besser, so ne Liste oder nen Fließtext?

**Comment by chr4** [comment]
> Da find ich den ersten auch am besten, würde aber das "or ..." wahrscheinlich sogar raus nehmen.

Also nur "town"? Mir fiehl es schwer irgendwas zu haben, was offen ist für andere  Use-Cases aber nicht zu sehr sich von unserem Ziel entfernt. Vielleicht irgendwas von wegen support local businesses und dann als Beispiele sowas wie trade assoc. oder eben Märkte...?

**Comment by fabrik42** [comment]
Also `organic market` steht imho definitiv für Biomarkt - Wenn es so gemeint ist, dann ok, wenn nicht, dann würde ich was anderes nehmen regional/local markets oder so?

> Also nur "town"? 

Ja stimmt schon. Ein Mix aus 1 und 2? With the CNDY ecosystem your local trade association can create a digital currency to support businesses in your area.

> Was findest du besser, so ne Liste oder nen Fließtext?

Ich glaube Fließtext ist besser, aber ist es ja eigentlich auch schon fast. :)

**Comment by chr4** [comment]
> With the CNDY ecosystem your local trade association can create a digital currency to support businesses in your area.

Ja das wäre ok - wollte halt was, das nicht nur nach "halt die Läden" aussieht, sondern weiter gefasst ist - Gewerbevereine, oder halt auch Dinge die es in Städten gibt. Aber nur businneses wäre sicherlich auch ok.

**Comment by chr4** [comment]
> Go in depth on **how** your project utilizes Stellar

Mmh, mir kommen mache der Punkte eher wie Stellar-Feierrei vor. Die wissen sicherlich, dass es gut ist kurze Transaktionszeiten zu haben, z.B.
Das **how** in der Frage kommt grade noch etwas zu kurz finde ich.

Hab die Sätze mal ausformuliert, aber in Bullet-Points gelassen. Finde es so eigentlich ganz nett.

**Comment by fabrik42** [comment]
> Mmh, mir kommen mache der Punkte eher wie Stellar-Feierrei vor. 

Hmm ja hast recht, da hab ich ein bisschen übertrieben. Sollte man eher auf die objektive Nutzung Beschränken.

**Comment by chr4** [comment]
Hab die Liste mal geupdated, jetzt:

> With the CNDY ecosystem your local trade association or organic food market can create a digital local currency to support local businesses

Wenn das so passt, würd ich das erstmal nehmen. Sind auch 140 chars :)

**Comment by fabrik42** [comment]
Ich habe die 20 Accounts erstellt und als Paper Wallet als PDFs bereitgestellt. Muss sie dann noch wo hochladen und würde den Link dann am Ende der Beschreibung anhängen?

**Comment by chr4** [comment]
Top. Geht das bei Netlify einfach?
